claimsmanager: improve test coverage
quicksilver-zone/quicksilver pull request #1548
Opened 2024-05-02 00:00 UTC by pysel

## 1. Summary
Fixes # (issue)

## 2.Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## 3. Implementation details

## 4. How to test/use

## 5. Checklist

- [ ] Does the Readme need to be updated?

## 6. Limitations (optional)

## 7. Future Work (optional)

2024-05-02 10:06 UTC, joe-bowman commented on x/claimsmanager/keeper/self_consensus_state_test.go
> +	err = k.StoreSelfConsensusState(ctx, "test-1")
err should be checked with `suite.NoError(err)`

2024-05-02 10:07 UTC, joe-bowman requested changes
check value of err please.

2024-05-07 01:25 UTC, pysel commented
hey @joe-bowman , error checked

2024-05-07 21:16 UTC, joe-bowman approved these changes
lgtm

2024-05-07 22:02 UTC, merged