Lint proto files
quicksilver-zone/quicksilver pull request #1565
Opened 2024-05-05 02:28 UTC by pysel

## 1. Summary
Fixes # (issue)

## 2.Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## 3. Implementation details

## 4. How to test/use

## 5. Checklist

- [ ] Does the Readme need to be updated?

## 6. Limitations (optional)

## 7. Future Work (optional)

2024-05-05 08:23 UTC, tropicaldog requested changes
after setup the Buf version to v1.21.0 and run `make proto-lint`, I got this: 

```
proto/quicksilver/airdrop/v1/airdrop.proto:16:3:Enum value name "ActionUndefined" should be prefixed with "ACTION_".
proto/quicksilver/airdrop/v1/airdrop.proto:16:3:Enum value name "ActionUndefined" should be UPPER_SNAKE_CASE, such as "ACTION_UNDEFINED".
proto/quicksilver/airdrop/v1/airdrop.proto:16:3:Enum zero value name "ActionUndefined" should be suffixed with "_UNSPECIFIED".
proto/quicksilver/airdrop/v1/airdrop.proto:18:3:Enum value name "ActionInitialClaim" should be prefixed with "ACTION_".
proto/quicksilver/airdrop/v1/airdrop.proto:18:3:Enum value name "ActionInitialClaim" should be UPPER_SNAKE_CASE, such as "ACTION_INITIAL_CLAIM".
proto/quicksilver/airdrop/v1/airdrop.proto:20:3:Enum value name "ActionDepositT1" should be prefixed with "ACTION_".
proto/quicksilver/airdrop/v1/airdrop.proto:20:3:Enum value name "ActionDepositT1" should be UPPER_SNAKE_CASE, such as "ACTION_DEPOSIT_T1".
proto/quicksilver/airdrop/v1/airdrop.proto:22:3:Enum value name "ActionDepositT2" should be prefixed with "ACTION_".
proto/quicksilver/airdrop/v1/airdrop.proto:22:3:Enum value name "ActionDepositT2" should be UPPER_SNAKE_CASE, such as "ACTION_DEPOSIT_T2".
proto/quicksilver/airdrop/v1/airdrop.proto:24:3:Enum value name "ActionDepositT3" should be prefixed with "ACTION_".
proto/quicksilver/airdrop/v1/airdrop.proto:24:3:Enum value name "ActionDepositT3" should be UPPER_SNAKE_CASE, such as "ACTION_DEPOSIT_T3".
proto/quicksilver/airdrop/v1/airdrop.proto:26:3:Enum value name "ActionDepositT4" should be prefixed with "ACTION_".
proto/quicksilver/airdrop/v1/airdrop.proto:26:3:Enum value name "ActionDepositT4" should be UPPER_SNAKE_CASE, such as "ACTION_DEPOSIT_T4".
proto/quicksilver/airdrop/v1/airdrop.proto:28:3:Enum value name "ActionDepositT5" should be prefixed with "ACTION_".
proto/quicksilver/airdrop/v1/airdrop.proto:28:3:Enum value name "ActionDepositT5" should be UPPER_SNAKE_CASE, such as "ACTION_DEPOSIT_T5".
proto/quicksilver/airdrop/v1/airdrop.proto:30:3:Enum value name "ActionStakeQCK" should be prefixed with "ACTION_".
proto/quicksilver/airdrop/v1/airdrop.proto:30:3:Enum value name "ActionStakeQCK" should be UPPER_SNAKE_CASE, such as "ACTION_STAKE_QCK".
proto/quicksilver/airdrop/v1/airdrop.proto:32:3:Enum value name "ActionSignalIntent" should be prefixed with "ACTION_".
proto/quicksilver/airdrop/v1/airdrop.proto:32:3:Enum value name "ActionSignalIntent" should be UPPER_SNAKE_CASE, such as "ACTION_SIGNAL_INTENT".
proto/quicksilver/airdrop/v1/airdrop.proto:34:3:Enum value name "ActionQSGov" should be prefixed with "ACTION_".
proto/quicksilver/airdrop/v1/airdrop.proto:34:3:Enum value name "ActionQSGov" should be UPPER_SNAKE_CASE, such as "ACTION_QS_GOV".
proto/quicksilver/airdrop/v1/airdrop.proto:36:3:Enum value name "ActionGbP" should be prefixed with "ACTION_".
proto/quicksilver/airdrop/v1/airdrop.proto:36:3:Enum value name "ActionGbP" should be UPPER_SNAKE_CASE, such as "ACTION_GB_P".
proto/quicksilver/airdrop/v1/airdrop.proto:38:3:Enum value name "ActionOsmosis" should be prefixed with "ACTION_".
proto/quicksilver/airdrop/v1/airdrop.proto:38:3:Enum value name "ActionOsmosis" should be UPPER_SNAKE_CASE, such as "ACTION_OSMOSIS".
proto/quicksilver/airdrop/v1/airdrop.proto:45:3:Enum value name "StatusUndefined" should be prefixed with "STATUS_".
proto/quicksilver/airdrop/v1/airdrop.proto:45:3:Enum value name "StatusUndefined" should be UPPER_SNAKE_CASE, such as "STATUS_UNDEFINED".
proto/quicksilver/airdrop/v1/airdrop.proto:45:3:Enum zero value name "StatusUndefined" should be suffixed with "_UNSPECIFIED".
proto/quicksilver/airdrop/v1/airdrop.proto:46:3:Enum value name "StatusActive" should be prefixed with "STATUS_".
proto/quicksilver/airdrop/v1/airdrop.proto:46:3:Enum value name "StatusActive" should be UPPER_SNAKE_CASE, such as "STATUS_ACTIVE".
proto/quicksilver/airdrop/v1/airdrop.proto:47:3:Enum value name "StatusFuture" should be prefixed with "STATUS_".
proto/quicksilver/airdrop/v1/airdrop.proto:47:3:Enum value name "StatusFuture" should be UPPER_SNAKE_CASE, such as "STATUS_FUTURE".
proto/quicksilver/airdrop/v1/airdrop.proto:48:3:Enum value name "StatusExpired" should be prefixed with "STATUS_".
proto/quicksilver/airdrop/v1/airdrop.proto:48:3:Enum value name "StatusExpired" should be UPPER_SNAKE_CASE, such as "STATUS_EXPIRED".
proto/quicksilver/airdrop/v1/messages.proto:14:9:Service name "Msg" should be suffixed with "Service".
proto/quicksilver/airdrop/v1/messages.proto:15:13:RPC request type "MsgClaim" should be named "ClaimRequest" or "MsgClaimRequest".
proto/quicksilver/airdrop/v1/messages.proto:22:26:RPC request type "MsgIncentivePoolSpend" should be named "IncentivePoolSpendRequest" or "MsgIncentivePoolSpendRequest".
proto/quicksilver/airdrop/v1/query.proto:14:9:Service name "Query" should be suffixed with "Service".
proto/quicksilver/claimsmanager/v1/claimsmanager.proto:14:3:Enum value name "ClaimTypeUndefined" should be prefixed with "CLAIM_TYPE_".
proto/quicksilver/claimsmanager/v1/claimsmanager.proto:14:3:Enum value name "ClaimTypeUndefined" should be UPPER_SNAKE_CASE, such as "CLAIM_TYPE_UNDEFINED".
proto/quicksilver/claimsmanager/v1/claimsmanager.proto:14:3:Enum zero value name "ClaimTypeUndefined" should be suffixed with "_UNSPECIFIED".
proto/quicksilver/claimsmanager/v1/claimsmanager.proto:15:3:Enum value name "ClaimTypeLiquidToken" should be prefixed with "CLAIM_TYPE_".
proto/quicksilver/claimsmanager/v1/claimsmanager.proto:15:3:Enum value name "ClaimTypeLiquidToken" should be UPPER_SNAKE_CASE, such as "CLAIM_TYPE_LIQUID_TOKEN".
proto/quicksilver/claimsmanager/v1/claimsmanager.proto:16:3:Enum value name "ClaimTypeOsmosisPool" should be prefixed with "CLAIM_TYPE_".
proto/quicksilver/claimsmanager/v1/claimsmanager.proto:16:3:Enum value name "ClaimTypeOsmosisPool" should be UPPER_SNAKE_CASE, such as "CLAIM_TYPE_OSMOSIS_POOL".
proto/quicksilver/claimsmanager/v1/claimsmanager.proto:17:3:Enum value name "ClaimTypeCrescentPool" should be prefixed with "CLAIM_TYPE_".
proto/quicksilver/claimsmanager/v1/claimsmanager.proto:17:3:Enum value name "ClaimTypeCrescentPool" should be UPPER_SNAKE_CASE, such as "CLAIM_TYPE_CRESCENT_POOL".
proto/quicksilver/claimsmanager/v1/claimsmanager.proto:18:3:Enum value name "ClaimTypeSifchainPool" should be prefixed with "CLAIM_TYPE_".
proto/quicksilver/claimsmanager/v1/claimsmanager.proto:18:3:Enum value name "ClaimTypeSifchainPool" should be UPPER_SNAKE_CASE, such as "CLAIM_TYPE_SIFCHAIN_POOL".
proto/quicksilver/claimsmanager/v1/claimsmanager.proto:19:3:Enum value name "ClaimTypeUmeeToken" should be prefixed with "CLAIM_TYPE_".
proto/quicksilver/claimsmanager/v1/claimsmanager.proto:19:3:Enum value name "ClaimTypeUmeeToken" should be UPPER_SNAKE_CASE, such as "CLAIM_TYPE_UMEE_TOKEN".
proto/quicksilver/claimsmanager/v1/claimsmanager.proto:36:10:Field name "_amount" should be lower_snake_case, such as "amount".
proto/quicksilver/claimsmanager/v1/messages.proto:7:9:Service name "Msg" should be suffixed with "Service".
proto/quicksilver/claimsmanager/v1/query.proto:13:9:Service name "Query" should be suffixed with "Service".
proto/quicksilver/claimsmanager/v1/query.proto:15:3:"quicksilver.claimsmanager.v1.QueryClaimsRequest" is used as the request or response type for multiple RPCs.
proto/quicksilver/claimsmanager/v1/query.proto:15:3:"quicksilver.claimsmanager.v1.QueryClaimsResponse" is used as the request or response type for multiple RPCs.
proto/quicksilver/claimsmanager/v1/query.proto:20:3:"quicksilver.claimsmanager.v1.QueryClaimsRequest" is used as the request or response type for multiple RPCs.
proto/quicksilver/claimsmanager/v1/query.proto:20:3:"quicksilver.claimsmanager.v1.QueryClaimsResponse" is used as the request or response type for multiple RPCs.
proto/quicksilver/claimsmanager/v1/query.proto:20:23:RPC request type "QueryClaimsRequest" should be named "LastEpochClaimsRequest" or "QueryLastEpochClaimsRequest".
proto/quicksilver/cl [...]

2024-05-06 23:35 UTC, pysel commented
> after setup the Buf version to v1.21.0 and run `make proto-lint`, I got this:
> 
> Full linting output for Quicksilver's proto
> This PR has addressed some lint issues, but further work is needed to fully resolve all linting errors and warnings on quicksilver's proto.

yeah, there are many linting issues, I only fixed those that have popped up in my editor

2024-05-07 14:32 UTC, faddat commented
Can you update docs like the rabbit mentioned?

thanks :0

2024-05-07 18:37 UTC, pysel commented
> Can you update docs like the rabbit mentioned?
> 
> thanks :0

hey @faddat, done

2024-05-07 21:15 UTC, joe-bowman commented
It's not just docs that will be affected by this. The next run of `make proto-gen` will come with a whole bunch of changes to the code base.

Why the dropping of Msg and Query prefixes? These still seem to be common usage until at least cosmos-sdk v0.50.

2024-05-08 03:57 UTC, faddat commented
Personally my approach to linter-suggested naming changes is to slavishly accept them.  My reasoning for that is that when we slavishly accept these changes, we get a fixed standard for future use.

@pysel -- for this PR to work though, we would need to regenerate the .proto files and update the docs.

2024-05-13 14:24 UTC, faddat commented
@pysel we've still got some tests failing -- and I'll let @joe-bowman be the ultimate judge of weather or not to merge this, but .... yeah my stance is to keep bringing them in.

2024-05-13 14:45 UTC, faddat commented on proto/quicksilver/interchainquery/v1/query.proto
> +message QueriesResponse {
@pysel could you check this one out please?

2024-05-28 00:38 UTC, joe-bowman commented
This pull request has been automatically marked as stale because it has not had any recent activity. It will be closed if no further activity occurs. Thank you!

2024-06-16 00:42 UTC, joe-bowman commented
This pull request has been automatically marked as stale because it has not had any recent activity. It will be closed if no further activity occurs. Thank you!

2024-06-23 00:42 UTC, closed without merging