E2e/test
quicksilver-zone/quicksilver pull request #527
Opened 2023-08-09 12:49 UTC by rajrohit10

## 1. Summary
Fixes # (issue)
 Created a RegisterZone test  
 Updated dependencies to github.com/strangelove-ventures/interchaintest/v7 in test/interchaintest
 Updated some minor dependencies

## 2.Type of change

 
Adding a register-zone test file to the Interchain test script

## 3. Implementation details

## 4. How to test/use

## 5. Checklist

- [ ] Does the Readme need to be updated?

## 6. Limitations (optional)

## 7. Future Work (optional)

2023-08-09 13:24 UTC, aljo242 commented
@rajrohit10 lint failing

2023-08-17 18:18 UTC, ajansari95 requested changes
there seems to be some conflicts

2023-08-17 18:20 UTC, ajansari95 requested changes

2023-08-17 18:20 UTC, ajansari95 commented on test/interchaintest/setup.go
> +			ChainID:             "quicksilverd",
chain-id not in desired format

2023-08-17 18:20 UTC, ajansari95 commented on test/interchaintest/interchainstaking_test.go
> +	// require.NoError(t, err)
should be reverted

2023-08-17 18:20 UTC, ajansari95 commented on test/interchaintest/interchainstaking_test.go
> +	// require.NoError(t, err)
should be reverted

2023-08-17 18:20 UTC, ajansari95 commented on test/interchaintest/e2e_test.go
> +				ChainID:        "quicksilverd",
chain-id not in desired format

2023-08-18 11:36 UTC, rajrohit10 commented on test/interchaintest/setup.go
> +			ChainID:             "quicksilverd",
Corrected

2023-08-18 21:15 UTC, rajrohit10 commented on test/interchaintest/interchainstaking_test.go
> +	// require.NoError(t, err)
Will add in the next commit

2023-09-12 05:28 UTC, anhductn2001 commented
Hi @rajrohit10, I just checkout your branch and run ictest-registerzone. Now, the test is stuck due to len(connection) = 2. Can you check it?

2023-09-12 06:00 UTC, anhductn2001 commented
It seems this PR has an E2E part that overlaps with my previous PR #521 . So we will consider keeping the new changes and removing the duplicates.

2024-05-10 00:37 UTC, joe-bowman commented
This pull request has been automatically marked as stale because it has not had any recent activity. It will be closed if no further activity occurs. Thank you!

2024-05-25 00:36 UTC, joe-bowman commented
This pull request has been automatically marked as stale because it has not had any recent activity. It will be closed if no further activity occurs. Thank you!

2024-06-09 00:43 UTC, joe-bowman commented
This pull request has been automatically marked as stale because it has not had any recent activity. It will be closed if no further activity occurs. Thank you!

2024-06-24 00:41 UTC, joe-bowman commented
This pull request has been automatically marked as stale because it has not had any recent activity. It will be closed if no further activity occurs. Thank you!

2024-07-09 00:40 UTC, joe-bowman commented
This pull request has been automatically marked as stale because it has not had any recent activity. It will be closed if no further activity occurs. Thank you!

2024-07-24 00:41 UTC, joe-bowman commented
This pull request has been automatically marked as stale because it has not had any recent activity. It will be closed if no further activity occurs. Thank you!

2024-08-08 00:41 UTC, joe-bowman commented
This pull request has been automatically marked as stale because it has not had any recent activity. It will be closed if no further activity occurs. Thank you!

2024-08-24 00:40 UTC, joe-bowman commented
This pull request has been automatically marked as stale because it has not had any recent activity. It will be closed if no further activity occurs. Thank you!

2024-09-08 00:49 UTC, joe-bowman commented
This pull request has been automatically marked as stale because it has not had any recent activity. It will be closed if no further activity occurs. Thank you!

2024-09-23 00:47 UTC, joe-bowman commented
This pull request has been automatically marked as stale because it has not had any recent activity. It will be closed if no further activity occurs. Thank you!

2024-10-09 00:46 UTC, joe-bowman commented
This pull request has been automatically marked as stale because it has not had any recent activity. It will be closed if no further activity occurs. Thank you!

2024-10-09 09:40 UTC, closed without merging