Test for Zone
quicksilver-zone/quicksilver pull request #682
Opened 2023-10-09 08:21 UTC by DongLieu

## 1. Summary
Fixes #617

## 2.Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## 3. Implementation details

## 4. How to test/use

## 5. Checklist

- [ ] Does the Readme need to be updated?

## 6. Limitations (optional)

## 7. Future Work (optional)

2023-10-11 12:47 UTC, joe-bowman submitted a review, later dismissed
lgtm

2023-10-13 04:55 UTC, ThanhNhann commented on x/interchainstaking/keeper/grpc_query_test.go
> +		expectLength int
We don't use this, plz delete it

2023-10-13 05:00 UTC, ThanhNhann requested changes

2023-10-13 05:00 UTC, ThanhNhann commented on x/interchainstaking/keeper/grpc_query_test.go
> +			suite.NotNil(resp)
```suggestion
			if tc.wantErr {
				suite.T().Logf("Error:\n%v\n", err)
				suite.Error(err)
			} else {
				suite.NoError(err)
				suite.NotNil(resp)
			}
```

2023-10-13 06:36 UTC, ThanhNhann approved these changes

2023-10-13 08:24 UTC, anhductn2001 approved these changes

2023-10-13 08:25 UTC, merged